# Cloudflare Pages configuration
name = "dashboard-eletrize"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

# Environment variables are configured in Cloudflare Pages dashboard:
# Dashboard > Workers & Pages > dashboard-eletrize > Settings > Environment variables
#
# Required variables:
# HUBITAT_BASE_URL - Base URL for Hubitat API (without access_token parameter)
# HUBITAT_ACCESS_TOKEN - Your Hubitat access token